language: java
matrix:
  include:
    - os:  linux
      jdk: oraclejdk8
    - os: osx
      osx_image: xcode8.3

script: GRGIT_PASS= ./gradlew build gitPublishPush --stacktrace
before_cache:
- rm -f  $HOME/.gradle/caches/modules-2/modules-2.lock
- rm -fr $HOME/.gradle/caches/*/plugin-resolution/
- rm -fr $HOME/.gradle/caches/*/scripts/
cache:
  directories:
  - $HOME/.gradle/caches/
  - $HOME/.gradle/wrapper/
env:
  global:
    secure: "xFyGGEe9jt6Rw5jNotJcWozfnyvc5l1Ub3CXKHtFlX2udxOVx3IgZUOIFVGKexqdgelBSprttPSoMWlzRTd+mEM/7NaO4eQ5QyqXJjRcTC97aqbuhsA0dGaiSneD4PT9Y6hncAiGEmJpsI8Nn/5Ejq2NzjoTQik4w5CMzftHZADknskfxUtdtEnRTR30MwBdvBUoRIMwZtuNyLRfnHpEliLuR/piIMuuQ70FJmlCiBI+unVlJ+VQL1ghuPIPwwDJ6iMahT17EkqZlQgvscEYDPsTqJV5ZeFJF1+gFs3S7Lmz9OjXh7jtTKXyj0bryd6anenmMneA5ji4OfS+nxRjgdhdoqPI12/p6kqe067qPwLVXs+LFT7KaZWy2tUgQlciSDEsx4Ukl/KAYdn1umhTbTORjQcpzL+cxo09ZnmiNs4N0Ce/c8M6/UdQS5YOsEU8VyjCr2B9JENY/5huhYeIhYStCOx+ALX4Xu8eepQzUgXcfll9Yb4FuJbN9l9qgHP4yMkpxw7QbeZoRvx0UIEKQ+IysZ0GM1LTSSHDwWHZcwJcrlI3qFVnSq7uuPxXjxQZE6htQLuOHeV/qtRMaKG6+J30hH97P4oUJHVG/H9cGyCy6yLH3f0mfw+TmGxY2IcNmrb3aNm3f/+T8rYiMFD4D0qjVQvvNraizLwyBtmqjY0="
notifications:
  slack:
    on_success: change
    rooms:
      secure: 1pJzgkUfiSP/KX5TuAsAgKhFtaVcfVWwdK+rbHMpzX0herxB4aAtVh3V1EnkiOgPkCcehviLC5MsEDxgwMsLt7Ko7RQsZLd42w8dxv+cxQad4f3LPlej6G2QJMjO0+JeDDC++lBcYsj932buT7XqZQ37QYGuM2GOp3bOqwhZ0mpHgyQ/pWw+m0upiJL1Z/snjt6tLsQejUKFkl71omDleB/JPmgSDgXWIBBtPkR+J4ScH9cSXWgtuks30kk/BcI6NOGNDkieJb32K8xDxE8VlK7OY2TNGAEzHD4tFBHQMDLeWQvkc7tPWq9D4GZ2YyJpeq+wnKqu2xZOTkqq6hCDAHhaEGj8CPztHCsg1BdSc6Sq7yJxA8JDvWzh8v8nqRkhiIRPwAjX83DEJYvsA32ytQmibfBq2TEQMhiIDPp5H4YixdGqLxPCXFqR5H+JOwARllYCoMTbSxJimnfLdCFyFhXiX3LTne8GPJnoJx7nsizLSdJ4Ww8XdYmMAHP2QDBQFTdsJpHorm1/FCdqBXdcXNiY6vqRnGHzmiun+3cQEmHfwsiZ3pd4DFgaNjnjxc0zoW+0Qci7ybVtxG5xdFOg8jA/NvnDiEzdg20evNJk1WDboEuHg6eFjVJsjYhElQAcmZEgMjn24Ve/jAqxwcrcGIh5F6p3vmQWeBlgAdptbWU=
